import { LESSONS, THEME_LABELS } from './lessons.js';

export const CATEGORY_LABELS = THEME_LABELS;

// ---------- New original strategy cards (fill gaps the lesson quizzes don't cover) ----------
export const NEW_STRATEGY_CARDS = [
  { id: 'strategy:new:stop-placement', category: 'risk-management', q: "Where should a stop-loss typically sit relative to the pattern you're trading?", options: ["At a level that, if hit, proves the setup's premise wrong (e.g. below the pullback low)", 'A fixed 10% below entry no matter the setup', "There is no need for a fixed stop if you're watching the trade closely", 'At the exact entry price'], correct: 0, explain: "A stop belongs at the level that invalidates the reason you took the trade — not an arbitrary distance." },
  { id: 'strategy:new:position-sizing', category: 'risk-management', q: 'You have a $10,000 account and want to risk 1% per trade. Your stop is $0.50 away from entry. Roughly how many shares should you buy?', options: ['20 shares', '200 shares', '2,000 shares', '20,000 shares'], correct: 1, explain: '1% of $10,000 = $100 risk. $100 / $0.50 stop distance = 200 shares.' },
  { id: 'strategy:new:scaling-out', category: 'entry-exit', q: "What does 'scaling out' of a position mean?", options: ['Selling the entire position at once at a single price', 'Selling a portion of the position at one target and letting the rest ride toward a further target', 'Adding to a losing position to lower the average cost', 'Exiting only at a stop-loss'], correct: 1, explain: 'Scaling out locks in partial profit while leaving room for the trade to keep working.' },
  { id: 'strategy:new:averaging-down', category: 'risk-management', q: "Why is 'averaging down' (buying more as a losing trade drops further) considered risky?", options: ["It isn't risky — it lowers your average cost", "It adds size to a trade that's already proving the original thesis wrong, growing the loss if the decline continues", "It's only risky in options", 'It guarantees a better exit price'], correct: 1, explain: 'Adding to a loser compounds risk in a trade that price action is already arguing against.' },
  { id: 'strategy:new:premarket-prep', category: 'planning', q: 'What is the main purpose of premarket preparation (scanning, plan review) before the session opens?', options: ["It's optional busywork", 'To walk in with a plan and watchlist decided calmly, before live P&L and emotion are in play', 'To guarantee a winning trade', 'It only matters for options traders'], correct: 1, explain: 'Decisions made calmly beforehand hold up better than decisions made live under pressure.' },
  { id: 'strategy:new:theta-risk', category: 'options-crypto', q: 'Why does buying a short-dated option (close to expiration) carry more time-decay risk than a longer-dated one?', options: ["It doesn't — time decay is the same regardless of expiration", "Theta decay accelerates as expiration approaches, eroding the option's value faster with each passing day", 'Short-dated options have no theta decay', 'Only put options experience theta decay'], correct: 1, explain: "Theta decay isn't linear — it speeds up in the final weeks or days before expiration." },
  { id: 'strategy:new:crypto-leverage', category: 'options-crypto', q: 'Why is high leverage (e.g. 50x) especially dangerous in crypto perpetual futures?', options: ["It isn't dangerous if you're confident in the trade", 'A small adverse price move can trigger liquidation, wiping the position, because the margin cushion is so thin', 'Leverage only affects profits, never losses', 'Exchanges refund liquidated positions'], correct: 1, explain: 'At high leverage, only a tiny adverse move is needed to erase the margin backing the position.' },
  { id: 'strategy:new:overtrading', category: 'psychology', q: "What is 'overtrading'?", options: ['Taking more trades than your plan or edge justifies, often out of boredom or after a loss', 'Any day with more than one trade', 'Trading with too little size', 'Something that only applies to day traders, not swing traders'], correct: 0, explain: 'Overtrading means trading outside your actual edge or plan, usually chasing action rather than a real setup.' },
  { id: 'strategy:new:confirmation-vs-anticipation', category: 'entry-exit', q: "What's the difference between entering 'on confirmation' versus 'in anticipation' of a move?", options: ['There is no difference', 'Confirmation waits for price to actually break or hold a level before entering; anticipation enters before that proof, betting it will happen', 'Anticipation is always the safer approach', 'Confirmation entries always have worse risk/reward'], correct: 1, explain: 'Confirmation entries wait for the market to prove the move is happening; anticipation entries guess it will.' },
  { id: 'strategy:new:journaling-purpose', category: 'process-review', q: 'What is the main reason for keeping a detailed trade journal?', options: ["It's required by brokers", "Reviewing entries, exits, and process over many trades reveals patterns a single trade's P&L can't show", 'Only to track taxes', 'It replaces the need for a trading plan'], correct: 1, explain: "A journal's value comes from reviewing many trades together — patterns that don't show up in any single result." },
];

export function getStrategyCards(){
  const fromLessons = LESSONS.flatMap(lesson =>
    lesson.quiz.map((q, qi) => ({
      id: `strategy:${lesson.id}:${qi}`, deck: 'strategy', category: lesson.theme,
      q: q.q, options: q.options, correct: q.correct, explain: q.explain,
    }))
  );
  const fromNew = NEW_STRATEGY_CARDS.map(c => ({ ...c, deck: 'strategy' }));
  return fromLessons.concat(fromNew);
}
